### ISSUE TITLE
Tuple destructures into union of fst & snd

### ISSUE THREAD

**Issue by SamHH** [gigobyte/purify#84] opened 2019-03-18 18:06 UTC
TS: `3.3.3333`
purify: `0.12.2`

According to [the docs](https://gigobyte.github.io/purify/adts/Tuple#[Symbol.iterator]), it should be possible to destructure a tuple with each side retaining its correct type. It's typing as a union of `fst` and `snd` instead.

Repro:
```typescript
import { Tuple } from 'purify-ts/Tuple';

const [a, b] = Tuple(1, 'hello');
// Expected: [number, string]
// Actual: [string | number, string | number]
```

**Comment by gigobyte** [comment] 2019-03-18 18:41
This seems to be either a TypeScript regression or I've accidentally used something that was fixed in 3.3 because in TS 2.2 your code snippet works.

**Comment by gigobyte** [comment] 2019-04-21 11:33
@SamHH, I've been going back to this issue and for me it seems like the types are still fine, I think only the TS reporting logic is giving the wrong hints to the editor. For example:

|Hovering at the declaration|Actually using the variable|
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/8791446/56469411-36b59600-6442-11e9-99ea-c7421dcfa165.png)| ![image](https://user-images.githubusercontent.com/8791446/56469427-66649e00-6442-11e9-8c36-8630831ad68a.png) |

I hope that clears things up!

**Closed** 2019-04-21 11:34 UTC
Labels: bug, regression

**Comment by SamHH** [comment] 2019-04-24 14:31
You're right, what a bizarre issue. Thanks for looking into it.
